---
abstract: 'commons.vote DB backend.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0.22
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.03
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Commons-Vote-Backend
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Utils: 0
  Data::Commons::Vote::Competition: 0
  Data::Commons::Vote::HashType: 0
  Data::Commons::Vote::Image: 0
  Data::Commons::Vote::Person: 0
  Data::Commons::Vote::PersonLogin: 0
  Data::Commons::Vote::Section: 0
  DateTime: 0
  DateTime::Format::Strptime: 0
  Encode: 0
  Error::Pure: 0
  Unicode::UTF8: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Commons-Vote-Backend/issues
  homepage: https://github.com/michal-josef-spacek/Commons-Vote-Backend
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Commons-Vote-Backend
version: '0.01'
