---
abstract: 'DB backend for commons.vote application.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  DBD::SQLite: 0
  English: 0
  Error::Pure::Utils: 0.22
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.03
  File::Spec::Functions: 0
  File::Temp: 0
  Schema::Commons::Vote: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Backend-DB-Commons-Vote
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Utils: 0
  Data::Commons::Vote::Competition: 0
  Data::Commons::Vote::HashType: 0
  Data::Commons::Vote::Image: 0
  Data::Commons::Vote::Person: 0
  Data::Commons::Vote::PersonLogin: 0
  Data::Commons::Vote::Section: 0
  Encode: 0
  Error::Pure: 0
  Unicode::UTF8: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Backend-DB-Commons-Vote/issues
  homepage: https://github.com/michal-josef-spacek/Backend-DB-Commons-Vote
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Backend-DB-Commons-Vote
version: '0.01'
